[project]
name = "pyproject"
version = "0.1.0"
description = ""
authors = [
    {name = "thuyhung8789",email = "hathithuydtvt@gmail.com"}
]
requires-python = ">=3.10"
dependencies = [
    "faker (>=40.31.0,<41.0.0)",
    "pandas (>=3.0.3,<4.0.0)",
    "psycopg2-binary (>=2.9.9)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "sqlalchemy (>=2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
